name: print on external push

on:
  repository_dispatch:
    types: [sample_push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print
        run: echo Hello





